/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trips` | `/trips`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buy` | `/buy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/checkin` | `/checkin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trips` | `/trips`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/buy` | `/buy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/checkin` | `/checkin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/users`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trips${`?${string}` | `#${string}` | ''}` | `/trips${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/buy${`?${string}` | `#${string}` | ''}` | `/buy${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/checkin${`?${string}` | `#${string}` | ''}` | `/checkin${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/admin/users${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trips` | `/trips`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/buy` | `/buy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/checkin` | `/checkin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; };
    }
  }
}
