/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/criar-conta/criar-conta`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-trips` | `/my-trips`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trips` | `/trips`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; } | { pathname: `/criar-conta`; params?: Router.UnknownInputParams; } | { pathname: `/login/Login`; params?: Router.UnknownInputParams; } | { pathname: `/trips`; params?: Router.UnknownInputParams; } | { pathname: `/trips/mine`; params?: Router.UnknownInputParams; } | { pathname: `/ticket/[userTripId]`, params: Router.UnknownInputParams & { userTripId: string | number; } } | { pathname: `/trips/[tripId]`, params: Router.UnknownInputParams & { tripId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/criar-conta/criar-conta`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-trips` | `/my-trips`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trips` | `/trips`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/users`; params?: Router.UnknownOutputParams; } | { pathname: `/criar-conta`; params?: Router.UnknownOutputParams; } | { pathname: `/login/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/trips`; params?: Router.UnknownOutputParams; } | { pathname: `/trips/mine`; params?: Router.UnknownOutputParams; } | { pathname: `/ticket/[userTripId]`, params: Router.UnknownOutputParams & { userTripId: string; } } | { pathname: `/trips/[tripId]`, params: Router.UnknownOutputParams & { tripId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/criar-conta/criar-conta${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-trips${`?${string}` | `#${string}` | ''}` | `/my-trips${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trips${`?${string}` | `#${string}` | ''}` | `/trips${`?${string}` | `#${string}` | ''}` | `/admin/users${`?${string}` | `#${string}` | ''}` | `/criar-conta${`?${string}` | `#${string}` | ''}` | `/login/Login${`?${string}` | `#${string}` | ''}` | `/trips${`?${string}` | `#${string}` | ''}` | `/trips/mine${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/criar-conta/criar-conta`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-trips` | `/my-trips`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trips` | `/trips`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; } | { pathname: `/criar-conta`; params?: Router.UnknownInputParams; } | { pathname: `/login/Login`; params?: Router.UnknownInputParams; } | { pathname: `/trips`; params?: Router.UnknownInputParams; } | { pathname: `/trips/mine`; params?: Router.UnknownInputParams; } | `/ticket/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/trips/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/ticket/[userTripId]`, params: Router.UnknownInputParams & { userTripId: string | number; } } | { pathname: `/trips/[tripId]`, params: Router.UnknownInputParams & { tripId: string | number; } };
    }
  }
}
